# Traitement & Nettoyages des donnees provenant de webscrapper

In [503]:
import pandas as pd # type: ignore
import numpy as np # type: ignore

## Je lis mes datasets

In [504]:
chiens = pd.read_csv("./data/chiens.csv")
moutons = pd.read_csv("./data/moutons.csv")
volailles = pd.read_csv("./data/volailles.csv")
other_animals = pd.read_csv("./data/other-animals.csv")

# Tratement du datasets Motos

## Obsertations

In [505]:
chiens.head()

,web-scraper-order,web-scraper-start-url,links,links-href,name,price,adresse,image-link-src
0,1739070143-1,https://sn.coinafrique.com/categorie/chiens?pa...,Pitt Bull red nose femelle,https://sn.coinafrique.com/annonce/chiens/pitt...,Pitt Bull red nose femelle,Prix sur demande,"Dakar, Sénégal","background-image: url(""https://images.coinafri..."
1,1739070148-2,https://sn.coinafrique.com/categorie/chiens?pa...,Chiots Pitbull,https://sn.coinafrique.com/annonce/chiens/chio...,Chiots Pitbull,250 000 CFA,"Grand Yoff, Dakar, Sénégal","background-image: url(""https://images.coinafri..."
2,1739070153-3,https://sn.coinafrique.com/categorie/chiens?pa...,Caniche bichon,https://sn.coinafrique.com/annonce/chiens/cani...,Caniche bichon,200 000 CFA,"Mermoz-Sacré Coeur, Dakar, Sénégal","background-image: url(""https://images.coinafri..."
3,1739070157-4,https://sn.coinafrique.com/categorie/chiens?pa...,Chiot Boerboel,https://sn.coinafrique.com/annonce/chiens/chio...,Chiot Boerboel,450 000 CFA,"Mermoz-Sacré Coeur, Dakar, Sénégal","background-image: url(""https://images.coinafri..."
4,1739070162-5,https://sn.coinafrique.com/categorie/chiens?pa...,Pitbull Red Nose,https://sn.coinafrique.com/annonce/chiens/pitb...,Pitbull Red Nose,220 000 CFA,"Mermoz-Sacré Coeur, Dakar, Sénégal","background-image: url(""https://images.coinafri..."

In [506]:
chiens["links-href"].iloc[0] 
# C'est pour voir si cette feature correspond au lien d'access de chaque page d'article -> c'est le cas

'https://sn.coinafrique.com/annonce/chiens/pitt-bull-red-nose-femelle-742530'

In [507]:
chiens.columns

Index(['web-scraper-order', 'web-scraper-start-url', 'links', 'links-href',
       'name', 'price', 'adresse', 'image-link-src'],
      dtype='object')

In [508]:
chiens.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 801 entries, 0 to 800
Data columns (total 8 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   web-scraper-order      801 non-null    object
 1   web-scraper-start-url  801 non-null    object
 2   links                  801 non-null    object
 3   links-href             801 non-null    object
 4   name                   801 non-null    object
 5   price                  801 non-null    object
 6   adresse                801 non-null    object
 7   image-link-src         801 non-null    object
dtypes: object(8)
memory usage: 50.2+ KB

In [509]:
chiens.describe().transpose()

,count,unique,top,freq
web-scraper-order,801,801,1739073284-801,1
web-scraper-start-url,801,10,https://sn.coinafrique.com/categorie/chiens?pa...,84
links,801,389,Chiot Berger Allemand,35
links-href,801,801,https://sn.coinafrique.com/annonce/chiens/chio...,1
name,801,389,Chiot Berger Allemand,35
price,801,78,Prix sur demande,155
adresse,801,52,"Dakar, Sénégal",173
image-link-src,801,801,"background-image: url(""https://images.coinafri...",1

### <font color="yellow"> Traitement gnrale

In [510]:
all_df = {"chiens": chiens, "moutons": moutons, "volailles": volailles, "other-animals": other_animals}

In [511]:
# Je redefinis mes col pour prendre que les cols concernees
new_columns = ['links-href', 'name', 'price', 'adresse', 'image-link-src']

for key, df in all_df.items():

    new_df = df[new_columns]

    # Je renomme la col image-link-src to image-link, et links-href to page-link
    new_df = new_df.rename({'image-link-src': "image-link","links-href": "page-link"}, axis=1)

    # je valide dans le all_df original
    all_df[key] = new_df

In [512]:
# un coup d'oeil
all_df["chiens"].head()

,page-link,name,price,adresse,image-link
0,https://sn.coinafrique.com/annonce/chiens/pitt...,Pitt Bull red nose femelle,Prix sur demande,"Dakar, Sénégal","background-image: url(""https://images.coinafri..."
1,https://sn.coinafrique.com/annonce/chiens/chio...,Chiots Pitbull,250 000 CFA,"Grand Yoff, Dakar, Sénégal","background-image: url(""https://images.coinafri..."
2,https://sn.coinafrique.com/annonce/chiens/cani...,Caniche bichon,200 000 CFA,"Mermoz-Sacré Coeur, Dakar, Sénégal","background-image: url(""https://images.coinafri..."
3,https://sn.coinafrique.com/annonce/chiens/chio...,Chiot Boerboel,450 000 CFA,"Mermoz-Sacré Coeur, Dakar, Sénégal","background-image: url(""https://images.coinafri..."
4,https://sn.coinafrique.com/annonce/chiens/pitb...,Pitbull Red Nose,220 000 CFA,"Mermoz-Sacré Coeur, Dakar, Sénégal","background-image: url(""https://images.coinafri..."

#### Nettoyage des textes

In [513]:
chiens = all_df["chiens"]

In [514]:
chiens.head()

,page-link,name,price,adresse,image-link
0,https://sn.coinafrique.com/annonce/chiens/pitt...,Pitt Bull red nose femelle,Prix sur demande,"Dakar, Sénégal","background-image: url(""https://images.coinafri..."
1,https://sn.coinafrique.com/annonce/chiens/chio...,Chiots Pitbull,250 000 CFA,"Grand Yoff, Dakar, Sénégal","background-image: url(""https://images.coinafri..."
2,https://sn.coinafrique.com/annonce/chiens/cani...,Caniche bichon,200 000 CFA,"Mermoz-Sacré Coeur, Dakar, Sénégal","background-image: url(""https://images.coinafri..."
3,https://sn.coinafrique.com/annonce/chiens/chio...,Chiot Boerboel,450 000 CFA,"Mermoz-Sacré Coeur, Dakar, Sénégal","background-image: url(""https://images.coinafri..."
4,https://sn.coinafrique.com/annonce/chiens/pitb...,Pitbull Red Nose,220 000 CFA,"Mermoz-Sacré Coeur, Dakar, Sénégal","background-image: url(""https://images.coinafri..."

In [515]:
def get_price_numeric(price:str):
    new_price = "".join(price.split(" ")[:-1])
    return new_price if new_price != "Prixsur" else np.nan

In [516]:
# Mettre en forme "marque"
# Separer le price en deux col: "price -> float" ete "devise" -> object
for key, df in all_df.items():

    price = df["price"].apply(get_price_numeric).astype(float)
    devise = df["price"].str.split(" ").str[-1]

    all_df[key]["price"] = price
    all_df[key]["devise"] = devise

    # Je profite pour juste recuperer le nom du quartier dans "adresse"
    quartier = df["adresse"].str.split(" ").str[0]
    ville = df["adresse"].str.split(" ").str[-2]
    pays = df["adresse"].str.split(" ").str[-1]

    all_df[key]["quartier"] = quartier
    all_df[key]["ville"] = ville
    all_df[key]["pays"] = pays

    all_df[key]["adresse"] = df["adresse"].str.strip()

In [517]:
chiens.head()

,page-link,name,price,adresse,image-link,devise,quartier,ville,pays
0,https://sn.coinafrique.com/annonce/chiens/pitt...,Pitt Bull red nose femelle,NaN,"Dakar, Sénégal","background-image: url(""https://images.coinafri...",demande,"Dakar,","Dakar,",Sénégal
1,https://sn.coinafrique.com/annonce/chiens/chio...,Chiots Pitbull,250000.0,"Grand Yoff, Dakar, Sénégal","background-image: url(""https://images.coinafri...",CFA,Grand,"Dakar,",Sénégal
2,https://sn.coinafrique.com/annonce/chiens/cani...,Caniche bichon,200000.0,"Mermoz-Sacré Coeur, Dakar, Sénégal","background-image: url(""https://images.coinafri...",CFA,Mermoz-Sacré,"Dakar,",Sénégal
3,https://sn.coinafrique.com/annonce/chiens/chio...,Chiot Boerboel,450000.0,"Mermoz-Sacré Coeur, Dakar, Sénégal","background-image: url(""https://images.coinafri...",CFA,Mermoz-Sacré,"Dakar,",Sénégal
4,https://sn.coinafrique.com/annonce/chiens/pitb...,Pitbull Red Nose,220000.0,"Mermoz-Sacré Coeur, Dakar, Sénégal","background-image: url(""https://images.coinafri...",CFA,Mermoz-Sacré,"Dakar,",Sénégal

In [518]:
chiens[["name", "price", "devise", "quartier", "ville", "pays", "adresse"]]

,name,price,devise,quartier,ville,pays,adresse
0,Pitt Bull red nose femelle,NaN,demande,"Dakar,","Dakar,",Sénégal,"Dakar, Sénégal"
1,Chiots Pitbull,250000.0,CFA,Grand,"Dakar,",Sénégal,"Grand Yoff, Dakar, Sénégal"
2,Caniche bichon,200000.0,CFA,Mermoz-Sacré,"Dakar,",Sénégal,"Mermoz-Sacré Coeur, Dakar, Sénégal"
3,Chiot Boerboel,450000.0,CFA,Mermoz-Sacré,"Dakar,",Sénégal,"Mermoz-Sacré Coeur, Dakar, Sénégal"
4,Pitbull Red Nose,220000.0,CFA,Mermoz-Sacré,"Dakar,",Sénégal,"Mermoz-Sacré Coeur, Dakar, Sénégal"
...,...,...,...,...,...,...,...
796,Chiot,500000.0,CFA,"Yoff,","Dakar,",Sénégal,"Yoff, Dakar, Sénégal"
797,Chiot Rottweiler,350000.0,CFA,"Sacré-Coeur,","Dakar,",Sénégal,"Sacré-Coeur, Dakar, Sénégal"
798,Chiot Husky,350000.0,CFA,"Sacré-Coeur,","Dakar,",Sénégal,"Sacré-Coeur, Dakar, Sénégal"
799,Chiot Chihuahua,150000.0,CFA,"Diamniadio,","Diamniadio,",Sénégal,"Diamniadio, Sénégal"
800,Chiot Berger Allemand,350000.0,CFA,"Diamniadio,","Diamniadio,",Sénégal,"Diamniadio, Sénégal"

In [519]:
chiens.head()

,page-link,name,price,adresse,image-link,devise,quartier,ville,pays
0,https://sn.coinafrique.com/annonce/chiens/pitt...,Pitt Bull red nose femelle,NaN,"Dakar, Sénégal","background-image: url(""https://images.coinafri...",demande,"Dakar,","Dakar,",Sénégal
1,https://sn.coinafrique.com/annonce/chiens/chio...,Chiots Pitbull,250000.0,"Grand Yoff, Dakar, Sénégal","background-image: url(""https://images.coinafri...",CFA,Grand,"Dakar,",Sénégal
2,https://sn.coinafrique.com/annonce/chiens/cani...,Caniche bichon,200000.0,"Mermoz-Sacré Coeur, Dakar, Sénégal","background-image: url(""https://images.coinafri...",CFA,Mermoz-Sacré,"Dakar,",Sénégal
3,https://sn.coinafrique.com/annonce/chiens/chio...,Chiot Boerboel,450000.0,"Mermoz-Sacré Coeur, Dakar, Sénégal","background-image: url(""https://images.coinafri...",CFA,Mermoz-Sacré,"Dakar,",Sénégal
4,https://sn.coinafrique.com/annonce/chiens/pitb...,Pitbull Red Nose,220000.0,"Mermoz-Sacré Coeur, Dakar, Sénégal","background-image: url(""https://images.coinafri...",CFA,Mermoz-Sacré,"Dakar,",Sénégal

# Traitement des valeurs manquantes

In [520]:
for key, df in all_df.items():
    print(f"{key}\n", df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 801 entries, 0 to 800
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   page-link   801 non-null    object
 1   name        801 non-null    object
 2   price       646 non-null    float64
 3   adresse     801 non-null    object
 4   image-link  801 non-null    object
 5   devise      801 non-null    object
 6   quartier    801 non-null    object
 7   ville       801 non-null    object
 8   pays        801 non-null    object
dtypes: float64(1), object(8)
memory usage: 56.4+ KB
chiens
 None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 840 entries, 0 to 839
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   page-link   840 non-null    object
 1   name        840 non-null    object
 2   price       684 non-null    float64
 3   adresse     840 non-null    object
 4   image-link  840 non-null    object
 5   devise      840 non-null    object
 6   quartier    840 non-null    object
 7   ville       840 non-null    object
 8   pays        840 non-null    object
dtypes: float64(1), object(8)
memory usage: 59.2+ KB
moutons
 None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 770 entries, 0 to 769
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   page-link   770 non-null    object
 1   name        770 non-null    object
 2   price       611 non-null    float64
 3   adresse     770 non-null    object
 4   image-link  770 non-null    object
 5   devise      770 non-null    object
 6   quartier    770 non-null    object
 7   ville       760 non-null    object
 8   pays        770 non-null    object
dtypes: float64(1), object(8)
memory usage: 54.3+ KB
volailles
 None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 436 entries, 0 to 435
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   page-link   436 non-null    object
 1   name        436 non-null    object
 2   price       326 non-null    float64
 3   adresse     436 non-null    object
 4   image-link  436 non-null    object
 5   devise      436 non-null    object
 6   quartier    436 non-null    object
 7   ville       431 non-null    object
 8   pays        436 non-null    object
dtypes: float64(1), object(8)
memory usage: 30.8+ KB
other-animals
 None

In [521]:
for key, df in all_df.items():
    price = df["price"].fillna(df["price"].mean())
    all_df[key]["price"] = price

In [522]:
for key, df in all_df.items():
    print(f"{key}\n", df.isnull().sum())

chiens
 page-link     0
name          0
price         0
adresse       0
image-link    0
devise        0
quartier      0
ville         0
pays          0
dtype: int64
moutons
 page-link     0
name          0
price         0
adresse       0
image-link    0
devise        0
quartier      0
ville         0
pays          0
dtype: int64
volailles
 page-link      0
name           0
price          0
adresse        0
image-link     0
devise         0
quartier       0
ville         10
pays           0
dtype: int64
other-animals
 page-link     0
name          0
price         0
adresse       0
image-link    0
devise        0
quartier      0
ville         5
pays          0
dtype: int64

In [523]:
chiens = pd.read_csv("./data/chiens.csv")
moutons = pd.read_csv("./data/moutons.csv")
volailles = pd.read_csv("./data/volailles.csv")
other_animals = pd.read_csv("./data/other-animals.csv")

# Sauvegarde des donnees nettoyees

In [525]:
for key, df in all_df.items():
    df.to_csv(f"./data-cleaned/{key}.csv", index=False)